# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mood_visual.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1366, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(1366, 720))
        Form.setMaximumSize(QtCore.QSize(1366, 720))
        self.mood_visual_background = QtWidgets.QLabel(Form)
        self.mood_visual_background.setGeometry(QtCore.QRect(0, 0, 1366, 720))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mood_visual_background.sizePolicy().hasHeightForWidth())
        self.mood_visual_background.setSizePolicy(sizePolicy)
        self.mood_visual_background.setMinimumSize(QtCore.QSize(1366, 720))
        self.mood_visual_background.setMaximumSize(QtCore.QSize(1366, 720))
        self.mood_visual_background.setStyleSheet("background-image: url(:/PrefixV1/images/mood visualization fg.png);")
        self.mood_visual_background.setText("")
        self.mood_visual_background.setObjectName("mood_visual_background")
        self.label_one_day_mood = QtWidgets.QLabel(Form)
        self.label_one_day_mood.setGeometry(QtCore.QRect(244, 255, 309, 309))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_one_day_mood.sizePolicy().hasHeightForWidth())
        self.label_one_day_mood.setSizePolicy(sizePolicy)
        self.label_one_day_mood.setMinimumSize(QtCore.QSize(0, 0))
        self.label_one_day_mood.setMaximumSize(QtCore.QSize(326, 325))
        self.label_one_day_mood.setStyleSheet("font: 700 italic 51pt \"Comic Sans MS\";")
        self.label_one_day_mood.setText("")
        self.label_one_day_mood.setObjectName("label_one_day_mood")
        self.label_one_week_mood = QtWidgets.QLabel(Form)
        self.label_one_week_mood.setGeometry(QtCore.QRect(703, 253, 517, 317))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_one_week_mood.sizePolicy().hasHeightForWidth())
        self.label_one_week_mood.setSizePolicy(sizePolicy)
        self.label_one_week_mood.setMinimumSize(QtCore.QSize(0, 0))
        self.label_one_week_mood.setMaximumSize(QtCore.QSize(1000, 1000))
        self.label_one_week_mood.setStyleSheet("font: 700 italic 51pt \"Comic Sans MS\";")
        self.label_one_week_mood.setText("")
        self.label_one_week_mood.setObjectName("label_one_week_mood")
        self.mood_visual_next = QtWidgets.QPushButton(Form)
        self.mood_visual_next.setGeometry(QtCore.QRect(1175, 618, 151, 68))
        self.mood_visual_next.setStyleSheet("selection-background-color: rgb(0, 255, 0);\n"
"border-image: url(:/PrefixV1/images/next button.png);")
        self.mood_visual_next.setText("")
        self.mood_visual_next.setFlat(True)
        self.mood_visual_next.setObjectName("mood_visual_next")
        self.mood_visual_select_date = QtWidgets.QPushButton(Form)
        self.mood_visual_select_date.setGeometry(QtCore.QRect(385, 636, 141, 33))
        self.mood_visual_select_date.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.mood_visual_select_date.setStyleSheet("font: 900 italic 16pt \"Segoe UI\";\n"
"color: rgb(168, 168, 168);")
        self.mood_visual_select_date.setObjectName("mood_visual_select_date")
        self.mood_visual_background.raise_()
        self.label_one_day_mood.raise_()
        self.label_one_week_mood.raise_()
        self.mood_visual_select_date.raise_()
        self.mood_visual_next.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.mood_visual_select_date.setText(_translate("Form", "SELECT"))
import Mood.resource_rc
