# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mood_input_rev1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1360, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(1360, 720))
        Form.setMaximumSize(QtCore.QSize(1360, 720))
        self.label = QtWidgets.QLabel(Form)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(0, 0, 1360, 720))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(1360, 720))
        self.label.setMaximumSize(QtCore.QSize(1360, 720))
        self.label.setStyleSheet("background-image: url(:/PrefixV1/images/mood input fg.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalSlider_joy = QtWidgets.QSlider(Form)
        self.horizontalSlider_joy.setGeometry(QtCore.QRect(185, 226, 375, 26))
        self.horizontalSlider_joy.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_joy.setObjectName("horizontalSlider_joy")
        self.horizontalSlider_sadness = QtWidgets.QSlider(Form)
        self.horizontalSlider_sadness.setGeometry(QtCore.QRect(185, 344, 375, 26))
        self.horizontalSlider_sadness.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_sadness.setObjectName("horizontalSlider_sadness")
        self.horizontalSlider_anger = QtWidgets.QSlider(Form)
        self.horizontalSlider_anger.setGeometry(QtCore.QRect(185, 459, 375, 26))
        self.horizontalSlider_anger.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_anger.setObjectName("horizontalSlider_anger")
        self.horizontalSlider_fear = QtWidgets.QSlider(Form)
        self.horizontalSlider_fear.setGeometry(QtCore.QRect(185, 573, 375, 26))
        self.horizontalSlider_fear.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_fear.setObjectName("horizontalSlider_fear")
        self.horizontalSlider_disgust = QtWidgets.QSlider(Form)
        self.horizontalSlider_disgust.setGeometry(QtCore.QRect(817, 226, 375, 26))
        self.horizontalSlider_disgust.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_disgust.setObjectName("horizontalSlider_disgust")
        self.horizontalSlider_surprise = QtWidgets.QSlider(Form)
        self.horizontalSlider_surprise.setGeometry(QtCore.QRect(817, 344, 375, 26))
        self.horizontalSlider_surprise.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_surprise.setObjectName("horizontalSlider_surprise")
        self.horizontalSlider_trust = QtWidgets.QSlider(Form)
        self.horizontalSlider_trust.setGeometry(QtCore.QRect(817, 459, 375, 26))
        self.horizontalSlider_trust.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_trust.setObjectName("horizontalSlider_trust")
        self.horizontalSlider_anticipation = QtWidgets.QSlider(Form)
        self.horizontalSlider_anticipation.setGeometry(QtCore.QRect(817, 573, 375, 26))
        self.horizontalSlider_anticipation.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_anticipation.setObjectName("horizontalSlider_anticipation")
        self.submitButtonMood = QtWidgets.QPushButton(Form)
        self.submitButtonMood.setGeometry(QtCore.QRect(1130, 650, 150, 50))
        self.submitButtonMood.setMinimumSize(QtCore.QSize(0, 50))
        self.submitButtonMood.setMaximumSize(QtCore.QSize(150, 50))
        self.submitButtonMood.setStyleSheet("\n"
"font: 700 20pt \"Segoe Script\";\n"
"alternate-background-color: rgb(255, 85, 0);\n"
"selection-color: rgb(170, 0, 0);\n"
"selection-background-color: rgb(170, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"border-image: url(:/PrefixV1/images/submit button.png);")
        self.submitButtonMood.setText("")
        icon = QtGui.QIcon.fromTheme("application-x-executable")
        self.submitButtonMood.setIcon(icon)
        self.submitButtonMood.setIconSize(QtCore.QSize(150, 50))
        self.submitButtonMood.setAutoDefault(False)
        self.submitButtonMood.setDefault(False)
        self.submitButtonMood.setFlat(False)
        self.submitButtonMood.setObjectName("submitButtonMood")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
import resource_rc
