# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testQuotesI4.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QGraphicsOpacityEffect
import Quotes.Quotes_Service as QS
from PyQt5.QtGui import QFont
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QTextCharFormat, QColor
import MainMenu.mainmenu as main


class QPopUp(QS.Quotes_Service):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1359, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 1361, 721))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(main.image_path))
        self.label_2.setObjectName("label_2")

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 1361, 720))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../image/Quotes/mendapat quotes fg black.png"))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QPlainTextEdit(MainWindow)
        self.label_4.setGeometry(QtCore.QRect(240, 395, 891, 151))
        # self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_4.setStyleSheet("background-color: transparent;")
        self.label_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        font = QtGui.QFont()
        font.setPointSize(18) 
        self.label_4.setFont(font)
        self.label_4.setPlainText(self.get_random_quote())
        self.label_4.setReadOnly(True)

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1180, 620, 151, 71))
        self.pushButton.setStyleSheet("background: transparent;")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.clickNext)
        # self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

    def clickNext(self):
        from MainMenu.main_menu_GUI import Main_Menu_GUI
        self.main_menu = Main_Menu_GUI()
        self.main_menu.show()
        self.hide()
    

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Dialog = QtWidgets.QDialog()
#     ui = QPopUp()
#     ui.setupUi(Dialog)
#     Dialog.show()
#     sys.exit(app.exec_())
