# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testQuotesI5.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import csv
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFont
# import MainMenu.mainmenu as main

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1366, 720))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1366, 720))
        self.label.setMinimumSize(QtCore.QSize(1366, 720))
        self.label.setMaximumSize(QtCore.QSize(1366, 720))
        self.label.setStyleSheet("border-image: url(./Quotes/image/quotes delete.png);")
        self.label.setText("")
        self.label.setObjectName("label")

        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(131, 342, 1101, 88))
        self.comboBox.setObjectName("comboBox")
        font = QFont("Arial", 15)
        self.comboBox.setFont(font)
        self.adding_quotes_Cbox()

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1071, 480, 150, 61))
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setStyleSheet("background-color: transparent;")
        self.pushButton.clicked.connect(self.submit)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setObjectName(u"backButton")
        self.backButton.setGeometry(QtCore.QRect(25, 25, 88, 86))
        self.backButton.setStyleSheet("QPushButton{background: transparent;}")
        self.backButton.clicked.connect(self.back)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
    
    def adding_quotes_Cbox(self):
        with open('Quotes/Quotes.csv', 'r') as csvfile:  # Replace with the name of your CSV file
            reader = csv.reader(csvfile)
            next(reader)
            for row in reader:
                quote = row[0] + ".  " + row[1]
                self.comboBox.addItem(quote)
    
    
    def submit(self):
        print("submit")
    
    def back(self):
        from Quotes.Choose_Call import Quotes_Choose_Call
        self.main_menu = Quotes_Choose_Call()
        self.main_menu.show()
        self.hide()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
