# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quotesawal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import csv
import random


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1359, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 1361, 721))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("background.jpg"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 1361, 720))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("getQuotes.png"))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(240, 395, 891, 151))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.openCSV()
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1180, 620, 151, 71))
        self.pushButton.setStyleSheet("background: transparent;")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.clickNext)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

    def clickNext(self):
        print("clicked")

    def openCSV(self):
        texts = []
        import csv
        with open('Quotes.csv', newline='') as csvfile:
            reader = csv.DictReader(csvfile)
            for row in reader:
                texts.append(row['Quote'])
                random_text = random.choice(texts)

                # Split text
                split_text = [random_text[i:i+80] if (i+80>=len(random_text)) or (random_text[i+80]==' ' or random_text[i+81]==' ') else random_text[i:i+80]+'-' for i in range(0, len(random_text), 80)]
                formatted_text = '\n'.join(split_text)

                # Set text
                font = QtGui.QFont()
                font.setPointSize(14) 
                self.label_4.setFont(font)
                self.label_4.setText(formatted_text)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
