# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\qtjournalinput.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from tkinter import messagebox
import Journal
import JournalDatabase
class JournalInput(object):
    DB = JournalDatabase.JournalDatabase()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 800)
        MainWindow.setMinimumSize(QtCore.QSize(599, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-image: url(:/Journal/background.jpg);")
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralwidget.setStyleSheet("background: transparent;\n"
"image: transparent;")
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setEnabled(True)
        self.widget.setGeometry(QtCore.QRect(0, -70, 1361, 941))
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("image: url(:/Journal/journal input fg.png);")
        self.widget.setObjectName("widget")
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setGeometry(QtCore.QRect(130, 380, 1101, 271))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.scrollArea.setFont(font)
        self.scrollArea.setStyleSheet("background: transparent;\n"
"image: transparent;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.ScrollAreaWidgetContents = QtWidgets.QWidget()
        self.ScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1099, 269))
        self.ScrollAreaWidgetContents.setObjectName("ScrollAreaWidgetContents")
        self.JournalContent = QtWidgets.QPlainTextEdit(self.ScrollAreaWidgetContents)
        self.JournalContent.setGeometry(QtCore.QRect(0, 0, 1101, 271))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.JournalContent.sizePolicy().hasHeightForWidth())
        self.JournalContent.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.JournalContent.setFont(font)
        self.JournalContent.setPlaceholderText("")
        self.JournalContent.setObjectName("JournalContent")
        self.scrollArea.setWidget(self.ScrollAreaWidgetContents)
        self.SubmitButton = QtWidgets.QPushButton(self.widget)
        self.SubmitButton.setEnabled(True)
        self.SubmitButton.setGeometry(QtCore.QRect(1060, 670, 171, 71))
        self.SubmitButton.setAutoFillBackground(False)
        self.SubmitButton.setStyleSheet("background: transparent;\n"
"image: transparent;")
        self.SubmitButton.setText("")
        self.SubmitButton.setFlat(True)
        self.SubmitButton.setObjectName("SubmitButton")
        self.SubmitButton.clicked.connect(self.addToJournalDB)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Journal Input"))
    def addToJournalDB(self):
        if self.JournalContent.toPlainText().strip()=="":
        # do nothing
                messagebox.showinfo("Failed", "Konten Jurnal kosong.")
        else : 
                addedContent = Journal.Journal([Journal.Journal.DatetimeToID(),self.JournalContent.toPlainText(),"Title"+Journal.Journal.DatetimeToID()])
                self.DB.addJournal(addedContent.toCSV())
                messagebox.showinfo("Success", "Konten Jurnal ditambahkan.")
import Journal_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = JournalInput()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())